# Generated by Django 5.0.3 on 2024-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subway_kl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subwayoutlet",
            name="retrieve_lat",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subwayoutlet",
            name="retrieve_long",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
