# Generated by Django 5.0.3 on 2024-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subway_kl", "0002_subwayoutlet_retrieve_lat_subwayoutlet_retrieve_long"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
            ],
        ),
    ]
