# Generated by Django 5.0.3 on 2024-03-11 11:57

from django.db import migrations


def populate_data(apps, schema_editor):
    # Your data manipulation logic goes here
    SubwayContext = apps.get_model("subway_kl", "SubwayContext")
    first_record = SubwayContext.objects.first()

    data = (
        "Bangsar have 1 outlets.\n"
        "1 outlets located in Bangsar.\n"
        "Bukit Damansara have 1 outlets.\n"
        "1 outlets located in Bukit Damansara.\n"
        "Sri hartamas have 1 outlets.\n"
        "1 outlets located in Sri hartamas.\n"
        "There is 67 outlets in Kuala Lumpur.\n"
        "Kuala Lumpur have 67 outlets.\n"
        "Subway Sri Gombak closes the latest.\n"
        "Subway Tesco Kepong open the latest.\n"
        "Subway University Malaya open the earliest.\n"
        "Subway Kidzania KL close at Tuesday.\n"
    )

    if first_record:
        # Update attributes for the first record
        first_record.context = data
        first_record.save()

    else:
        SubwayContext.objects.create(context=data)


class Migration(migrations.Migration):
    dependencies = [
        ("subway_kl", "0003_subwaycontext"),
    ]

    operations = [
        migrations.RunPython(
            populate_data,
        )
    ]
