repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--line-width=88",
            "--ensure-newline-before-comments",
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E501, W503, E226
          - --max-complexity=18
          - --max-line-length=88
        exclude: "__init__.py"
